apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: maria-configmap
# MariaDB 需要 4 个环境变量
data:
  DATABASE: 'db'
  USER: 'wp'
  PASSWORD: '123'
  ROOT_PASSWORD: '123'

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: maria-pod
    app: wordpress
    role: database
  name: maria-pod
spec:
  containers:
  - image: mariadb:10
    name: maria
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
    # envFrom 可以一次性地把 ConfigMap 里的字段全导入进 Pod
    # 并且能够指定变量名的前缀
    envFrom:
    - prefix: 'MARIADB_'
      configMapRef:
        name: maria-configmap
