apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: wordpress-configmap
data:
  HOST: '192.168.178.122'
  USER: 'wp'
  PASSWORD: '123'
  NAME: 'db'

---

apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels:
    app: wordpress
    role: website
spec:
  containers:
  - image: wordpress:5
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    name: wordpress
    
    envFrom:
    - prefix: 'WORDPRESS_DB_'
      configMapRef:
        name: wordpress-configmap